Add test for running on a Windows machine

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -496,6 +496,66 @@ jobs:
           RESULT="$(cat output | grep failure)"
           diff <(echo "$RESULT") <(echo "$EXPECTED")
 
+  run-on-windows:
+    name: Run cargo-semver-checks on Windows
+    runs-on: windows-latest
+    steps:
+      - name: Checkout cargo-semver-checks
+        uses: actions/checkout@v3
+        with:
+          persist-credentials: false
+
+      - name: Checkout test crate ref_slice baseline
+        uses: actions/checkout@v3
+        with:
+          persist-credentials: false
+          repository: mgr0dzicki/cargo-semver-action-ref-slice
+          path: 'subject-baseline'
+
+      - name: Checkout test crate ref_slice patch change
+        uses: actions/checkout@v3
+        with:
+          persist-credentials: false
+          repository: mgr0dzicki/cargo-semver-action-ref-slice
+          ref: 'patch_change'
+          path: 'subject-patch-change'
+
+      - name: Checkout test crate ref_slice major change
+        uses: actions/checkout@v3
+        with:
+          persist-credentials: false
+          repository: mgr0dzicki/cargo-semver-action-ref-slice
+          ref: 'major_change'
+          path: 'subject-major-change'
+
+      - name: Install rust
+        uses: actions-rs/toolchain@v1
+        with:
+          toolchain: stable
+          profile: minimal
+          override: true
+
+      - uses: Swatinem/rust-cache@v2
+        with:
+          key: windows
+
+      - name: Run semver-checks on the patch change
+        run: |
+          cargo run semver-checks check-release --manifest-path="subject-patch-change/Cargo.toml" \
+            --baseline-root="subject-baseline/Cargo.toml"
+
+      - name: Run semver-checks on the major change (allowed to fail)
+        run: |
+          cargo run semver-checks check-release --manifest-path="subject-major-change/Cargo.toml" \
+            --baseline-root="subject-baseline/Cargo.toml"         
+        continue-on-error: true
+
+      - name: Fail if the check on the major change has not returned any errors (but it should have)
+        if: steps.action_major.outcome != 'failure'
+        run: |
+          echo "Error! check-release should have failed because of the breaking change, but it has not."
+          exit 1         
+
   init-release:
     name: Run the release workflow
     needs:
